### ISSUE TITLE
[KOIN/Fix] 시간표 위젯 생성 시 IllegalArgumentException 발생

### ISSUE THREAD

**Issue by Jokwanhee** [BCSDLab/KOIN_ANDROID#184]
### 버그
- 코인 어플 시간표 위젯 생성 시, IllegalArgumentException 발생

**_에러 코드_**
```
FATAL EXCEPTION: main
Process: in.koreatech.koin, PID: 23419
java.lang.RuntimeException: Unable to start receiver
in.koreatech.koin.ui.timetable.TimetableWidget: java.lang.IllegalArgumentException: in.koreatech.koin: Targeting
S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be
specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some
functionality depends on the PendingIntent being mutable, e.g. if it needs to be
used with inline replies or bubbles.
at android.app.ActivityThread.handleReceiver(ActivityThread.java:4903)
at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2420)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8762)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.IllegalArgumentException: in.koreatech.koin: Targeting
S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be
specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some
functionality depends on the PendingIntent being mutable, e.g. if it needs to be
used with inline replies or bubbles.
at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:491)
at android.app.PendingIntent.getActivity(PendingIntent.java:477)
at android.app.PendingIntent.getActivity(PendingIntent.java:441)
at in.koreatech.koin.ui.timetable.TimetableWidget.updateAppWidget(TimetableWidget.java:56)
at in.koreatech.koin.ui.timetable.TimetableWidget.onUpdate(TimetableWidget.java:68)
at in.koreatech.koin.ui.timetable.TimetableWidget.onReceive(TimetableWidget.java:90)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:4894)
... 9 more
```

_**참고 영상**_

https://github.com/BCSDLab/KOIN_ANDROID/assets/90740783/fe7c0948-d85f-4c5d-adcd-f6a5acad2f67

**Comment by nayunjae** [comment]
@Jokwanhee  Android 12 변동 사항이라서 참고하면 좋은것 같아요.
[Android 12 Pending Intent 보안 이슈](https://developer.android.com/guide/components/intents-filters#CreateImmutablePendingIntents)

**Comment by Jokwanhee** [comment]
> @Jokwanhee Android 12 변동 사항이라서 참고하면 좋은것 같아요. [Android 12 Pending Intent 보안 이슈](https://developer.android.com/guide/components/intents-filters#CreateImmutablePendingIntents)

넵 감사합니다!!
